In [67]:
# Question 1
#What's the version of Pandas that you installed?
#You can get the version information using the __version__ field:

In [68]:
import pandas as pd

pd.__version__

'2.0.3'

In [69]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv

--2023-09-12 10:22:41--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.110.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1423529 (1.4M) [text/plain]
Saving to: ‘housing.csv’

housing.csv         100%[===================>]   1.36M  7.67MB/s    in 0.2s    

2023-09-12 10:22:41 (7.67 MB/s) - ‘housing.csv’ saved [1423529/1423529]



In [70]:
# Question 2
# How many columns are in the dataset?

In [71]:
df = pd.read_csv('housing.csv')

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [73]:
# Question 3
# Which columns in the dataset have missing values?

In [74]:
df.columns[df.isnull().any()].tolist()

['total_bedrooms']

In [75]:
# Question 4
# How many unique values does the ocean_proximity column have?

In [76]:
df["ocean_proximity"].unique().tolist()

['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND']

In [77]:
# Question 5
# What's the average value of the median_house_value for the houses located near the bay?

In [78]:
df_new = df[df['ocean_proximity'] == "NEAR BAY"]

In [79]:
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2290 entries, 0 to 19104
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           2290 non-null   float64
 1   latitude            2290 non-null   float64
 2   housing_median_age  2290 non-null   float64
 3   total_rooms         2290 non-null   float64
 4   total_bedrooms      2270 non-null   float64
 5   population          2290 non-null   float64
 6   households          2290 non-null   float64
 7   median_income       2290 non-null   float64
 8   median_house_value  2290 non-null   float64
 9   ocean_proximity     2290 non-null   object 
dtypes: float64(9), object(1)
memory usage: 196.8+ KB


In [80]:
df_new["median_house_value"].mean()

259212.31179039303

In [81]:
# Question 6
# Calculate the average of total_bedrooms column in the dataset.
# Use the fillna method to fill the missing values in total_bedrooms with the mean value from the previous step.
# Now, calculate the average of total_bedrooms again.
# Has it changed?

In [82]:
df["total_bedrooms"].mean()

537.8705525375618

In [83]:
newdf = df.fillna(537.870)

In [84]:
newdf["total_bedrooms"].mean()

537.870546996124

In [85]:
# Question 7
# Select all the options located on islands.
# Select only columns housing_median_age, total_rooms, total_bedrooms.
# Get the underlying NumPy array. Let's call it X.
# Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
# Compute the inverse of XTX.
# Create an array y with values [950, 1300, 800, 1000, 1300].
# Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
# What's the value of the last element of w?

In [86]:
df_islands = df[df['ocean_proximity'] == "ISLAND"]

In [87]:
df_islands.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 8314 to 8318
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           5 non-null      float64
 1   latitude            5 non-null      float64
 2   housing_median_age  5 non-null      float64
 3   total_rooms         5 non-null      float64
 4   total_bedrooms      5 non-null      float64
 5   population          5 non-null      float64
 6   households          5 non-null      float64
 7   median_income       5 non-null      float64
 8   median_house_value  5 non-null      float64
 9   ocean_proximity     5 non-null      object 
dtypes: float64(9), object(1)
memory usage: 440.0+ bytes


In [88]:
df_islands

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
8314    -118.32     33.35                27.0       1675.0           521.0   
8315    -118.33     33.34                52.0       2359.0           591.0   
8316    -118.32     33.33                52.0       2127.0           512.0   
8317    -118.32     33.34                52.0        996.0           264.0   
8318    -118.48     33.43                29.0        716.0           214.0   

      population  households  median_income  median_house_value  \
8314       744.0       331.0         2.1579            450000.0   
8315      1100.0       431.0         2.8333            414700.0   
8316       733.0       288.0         3.3906            300000.0   
8317       341.0       160.0         2.7361            450000.0   
8318       422.0       173.0         2.6042            287500.0   

     ocean_proximity  
8314          ISLAND  
8315          ISLAND  
8316          ISLAND  
8317          ISLAND  
8318          ISLAND

In [89]:
df_islands2 = df_islands[['housing_median_age', 'total_rooms', 'total_bedrooms']]

In [90]:
df_islands2

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [91]:
X = df_islands2.to_numpy()

In [92]:
X

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [93]:
X_T = X.transpose()

In [94]:
X_T

array([[  27.,   52.,   52.,   52.,   29.],
       [1675., 2359., 2127.,  996.,  716.],
       [ 521.,  591.,  512.,  264.,  214.]])

In [95]:
import numpy as np

XTX = np.matmul(X_T,X)
XTX

array([[9.6820000e+03, 3.5105300e+05, 9.1357000e+04],
       [3.5105300e+05, 1.4399307e+07, 3.7720360e+06],
       [9.1357000e+04, 3.7720360e+06, 9.9835800e+05]])

In [96]:
XTX_INV = np.linalg.inv(XTX)
XTX_INV

array([[ 9.19403586e-04, -3.66412216e-05,  5.43072261e-05],
       [-3.66412216e-05,  8.23303633e-06, -2.77534485e-05],
       [ 5.43072261e-05, -2.77534485e-05,  1.00891325e-04]])

In [97]:
y = np.array([950, 1300, 800, 1000, 1300])
y

array([ 950, 1300,  800, 1000, 1300])

In [98]:
w = np.matmul(np.matmul(XTX_INV,X_T), y)
w

array([23.12330961, -1.48124183,  5.69922946])